# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '班级表',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '单选题',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, '打分(1~10分)'), (2, '单选'), (3, '评价')])),
            ],
            options={
                'verbose_name_plural': '问题表',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('que2cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Class')),
            ],
            options={
                'verbose_name_plural': '问卷表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('stu2cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Class')),
            ],
            options={
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='que2user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.UserInfo'),
        ),
        migrations.AddField(
            model_name='question',
            name='que2quen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='option',
            name='opt2que',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='class',
            name='cls2user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.UserInfo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans2opt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans2que',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question', verbose_name='关联的第几题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ans2stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Student'),
        ),
    ]
