# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='num',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
